# Generated by Django 4.2.16 on 2024-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
