# Generated by Django 4.2.16 on 2024-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
